### PR TITLE
Adding navigational arrows

### PR DESCRIPTION
**Pull request by TheTieflingRngr**
I don’t know yet, just an idea I had on a whim

### CODE REVIEW

**Comment by TheTieflingRngr** [comment]
Again, this is on a whim, you may do whatever.

**Comment by RdrSeraphim** [comment]
Looks good to me. We can make sure these get integrated well into the GitHub Pages move too.

**Review by RdrSeraphim — APPROVED** [review]

**Comment by TheTieflingRngr** [comment]
GitHub pages didn’t have them by default, that’s why I made them.

**Comment by TheTieflingRngr** [comment]
GitHub pages didn’t have them by default, that’s why I made them.

**Pull request merged**
